[package]
name = "fivesou"
version = "0.2.0"
edition = "2021"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench_hand_scoring"
harness = false

[dependencies]
itertools = "0.13.0"
